-- 코드를 작성해주세요
SELECT i.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO i join ITEM_TREE t on i.ITEM_ID = t.ITEM_ID
WHERE PARENT_ITEM_ID in(SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY 1 desc